### ISSUE TITLE
Error following Quick Start

### ISSUE THREAD

**Issue by InvisibleFunction** [GalleyBytes/terraform-operator#112]
Hi, I'm trying to follow the [Quick Start](http://tf.isaaguilar.com/docs/getting-started/quick-start/) on the website and am encountering an error.

I'm using MacOS 12.5.1 and minikube v1.27.0. I installed terraform-operator by cloning the repo and using kubectl as documented.

The error I get is:
```
/usr/local/bin/entrypoint: line 24: wget: command not found
```
I see that the container image doesn't have wget:
```
$ docker run -it --entrypoint "wget" ghcr.io/galleybytes/terraform-operator-setup:1.0.0
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "wget": executable file not found in $PATH: unknown.
ERRO[0000] error waiting for container: context canceled 
```

It looks like the [script](https://github.com/GalleyBytes/terraform-operator-tasks/blob/master/images/entrypoint) seems to require wget under certain circumstances.

**Comment by isaaguilar** [comment]
@InvisibleFunction I reproduced the missing wget command on the arm64 image, but not the amd64 version. Turns out my base image for the arm architecture did not, in fact, contain wget. 

I will rebuild this and hopefully get some better tests before I push out a release. I have to admit, testing arm architecture is a bit of a stretch because all I have is a little raspberry pi. 

And thank you for posting the issue!
